### ISSUE TITLE
farmerbot: shouldn't we have at least one online node always?

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-go#594] opened 2024-01-01 20:14 UTC
Apparently in the previous farmerbot, there were at least 1 node by design excluded "manually excluded" by the farmer, to be able to send the WOL packets. Let's enforce it somehow, by either failing to start the farmerbot or use some sort of convention to exclude maybe the node with the least resources or the lowest node ID

**Comment by rawdaGastan** [comment] 2024-01-04 09:27
The node is excluded (the farmer bot cannot shut down a node if it is the last on node exists in the farm)
- the issue was (changing power target using tfchain failed, but it changed the power target of the node, that's why it turned off without the farmer bot notice)
- the issue is fixed by checking the power target of the node, even the chain failed to set it

tested here: https://github.com/threefoldtech/tf_operations/issues/2158

**Closed as completed** 2024-01-04 09:29 UTC
Labels: farmerbot
